# -*- coding: utf-8 -*-
"""gen_ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IyDpoxDwNNth0q8xqAVAdcf5r_xxArZJ

# 🛡️ Chat Toxicity Detection using BERT (Multi-Label Classification)

**Deep Learning – Formative Assessment II**  
**Problem Statement:** Classify online comments into multiple toxicity categories using BERT  
**Framework:** PyTorch + HuggingFace Transformers  
**Dataset:** Jigsaw Toxic Comment Classification (Kaggle / HuggingFace)

---

## Labels (Multi-Label):
| Label | Description |
|-------|-------------|
| `toxic` | General toxicity |
| `severe_toxic` | Highly offensive |
| `obscene` | Obscene language |
| `threat` | Threatening content |
| `insult` | Personal insults |
| `identity_hate` | Hate based on identity |
"""

!pip install transformers datasets scikit-learn matplotlib seaborn torch tqdm --quiet
print(' All libraries installed!')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import warnings
warnings.filterwarnings('ignore')

import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader

from transformers import (
    BertTokenizer,
    BertForSequenceClassification,
    get_linear_schedule_with_warmup
)

from torch.optim import AdamW

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    f1_score, roc_auc_score, classification_report,
    confusion_matrix, hamming_loss,
    precision_score, recall_score, accuracy_score
)

# GPU Check
if torch.cuda.is_available():
    device = torch.device('cuda')
    print(f'🖥️ Using GPU: {torch.cuda.get_device_name(0)}')
else:
    device = torch.device('cpu')
    print('🖥️ Using CPU')

df = pd.read_csv('/content/train.csv')
print(f"Full dataset shape: {df.shape}")
df.head()

LABEL_COLS = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

# Separate toxic and clean comments
toxic_df = df[df[LABEL_COLS].sum(axis=1) > 0]
clean_df = df[df[LABEL_COLS].sum(axis=1) == 0]

print(f"Total toxic  : {len(toxic_df):,}")
print(f"Total clean  : {len(clean_df):,}")


N_TOXIC = 6000
N_CLEAN = 6000

toxic_sample = toxic_df.sample(n=N_TOXIC, random_state=42)
clean_sample = clean_df.sample(n=N_CLEAN, random_state=42)

df_balanced = pd.concat([toxic_sample, clean_sample]).sample(frac=1, random_state=42).reset_index(drop=True)

print(f"\nBalanced dataset : {len(df_balanced):,} samples")
print(f"Toxic  : {df_balanced[LABEL_COLS].sum(axis=1).gt(0).sum():,}")
print(f"Clean  : {df_balanced[LABEL_COLS].sum(axis=1).eq(0).sum():,}")
print("\nLabel distribution:")
print(df_balanced[LABEL_COLS].sum().sort_values(ascending=False))

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Plot 1: Label frequency
label_counts = df_balanced[LABEL_COLS].sum().sort_values(ascending=False)
colors = ['#e74c3c','#e67e22','#f1c40f','#2ecc71','#3498db','#9b59b6']
axes[0].bar(label_counts.index, label_counts.values, color=colors, edgecolor='black')
axes[0].set_title('Label Frequency (Balanced Dataset)', fontsize=14, fontweight='bold')
axes[0].set_ylabel('Count')
axes[0].tick_params(axis='x', rotation=30)
for i, v in enumerate(label_counts.values):
    axes[0].text(i, v + 10, str(v), ha='center', fontsize=9, fontweight='bold')

# Plot 2: Labels per comment
df_balanced['label_count'] = df_balanced[LABEL_COLS].sum(axis=1)
vc = df_balanced['label_count'].value_counts().sort_index()
axes[1].bar(vc.index.astype(str), vc.values, color='#3498db', edgecolor='black')
axes[1].set_title('Labels per Comment', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Number of labels assigned')
axes[1].set_ylabel('Number of comments')

# Plot 3: Text length
df_balanced['text_len'] = df_balanced['comment_text'].astype(str).apply(lambda x: len(x.split()))
toxic_mask = df_balanced['toxic'] == 1
axes[2].hist(df_balanced[~toxic_mask]['text_len'].clip(0,300), bins=50, alpha=0.7, label='Non-toxic', color='#2ecc71')
axes[2].hist(df_balanced[ toxic_mask]['text_len'].clip(0,300), bins=50, alpha=0.7, label='Toxic',     color='#e74c3c')
axes[2].set_title('Comment Length (words)', fontsize=14, fontweight='bold')
axes[2].set_xlabel('Word Count (clipped at 300)')
axes[2].legend()

plt.tight_layout()
plt.savefig('eda_toxicity.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"Clean comments : {(df_balanced['label_count']==0).sum():,}")
print(f"Toxic comments : {(df_balanced['label_count']>0).sum():,}")

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df_balanced['clean_text'] = df_balanced['comment_text'].apply(clean_text)
print(df_balanced[['comment_text', 'clean_text']].head())

train_df, val_df = train_test_split(
    df_balanced, test_size=0.2, random_state=42, stratify=df_balanced['toxic']
)

print(f"Train size : {len(train_df):,}")
print(f"Val size   : {len(val_df):,}")

tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
MAX_LEN = 128
print(" Tokenizer loaded")

class ToxicDataset(Dataset):
    def __init__(self, df):
        self.texts  = df['clean_text'].values
        self.labels = df[LABEL_COLS].values

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        encoding = tokenizer(
            self.texts[idx],
            padding='max_length',
            truncation=True,
            max_length=MAX_LEN,
            return_tensors='pt'
        )
        return {
            'input_ids':      encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'labels':         torch.tensor(self.labels[idx], dtype=torch.float)
        }

sample = ToxicDataset(train_df)[0]
print("Sample keys :", list(sample.keys()))
print("Labels      :", sample['labels'])

model = BertForSequenceClassification.from_pretrained(
    'bert-base-uncased',
    num_labels=len(LABEL_COLS),
    problem_type="multi_label_classification",
    hidden_dropout_prob=0.3,           # was 0.1 — increased for regularization
    attention_probs_dropout_prob=0.3   # was 0.1
)
model = model.to(device)

# Freeze first 6 BERT encoder layers
for name, param in model.bert.encoder.layer[:6].named_parameters():
    param.requires_grad = False

total_params   = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Model loaded")
print(f"   Total params     : {total_params:,}")
print(f"   Trainable params : {trainable_params:,} ({100*trainable_params/total_params:.1f}%)")

BATCH_SIZE = 16
EPOCHS     = 6

train_dataset = ToxicDataset(train_df)
val_dataset   = ToxicDataset(val_df)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE)

# Lower LR + weight decay to reduce overfitting
optimizer = AdamW(model.parameters(), lr=1e-5, weight_decay=0.01)

total_steps = len(train_loader) * EPOCHS
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=int(0.1 * total_steps),
    num_training_steps=total_steps
)

# pos_weight: higher = model penalised more for missing that label
label_counts_train = train_df[LABEL_COLS].sum()
neg_counts         = len(train_df) - label_counts_train
pos_weight         = (neg_counts / (label_counts_train + 1e-6)).clip(upper=10).values
pos_weight_tensor  = torch.tensor(pos_weight, dtype=torch.float).to(device)

loss_fn = nn.BCEWithLogitsLoss(pos_weight=pos_weight_tensor)

print("pos_weight per label:")
for label, w in zip(LABEL_COLS, pos_weight):
    print(f"  {label:15s}: {w:.2f}")

from tqdm import tqdm

def train_epoch(model, data_loader, loss_fn, optimizer, device, scheduler):
    model.train()
    total_loss = 0
    bar = tqdm(data_loader, desc="Training", leave=True)
    for batch in bar:
        optimizer.zero_grad()
        input_ids      = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels         = batch['labels'].to(device)
        outputs        = model(input_ids=input_ids, attention_mask=attention_mask)
        loss           = loss_fn(outputs.logits, labels)
        total_loss    += loss.item()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()
        bar.set_postfix(loss=f"{loss.item():.4f}")
    return total_loss / len(data_loader)

def eval_model(model, data_loader, loss_fn, device):
    model.eval()
    total_loss  = 0
    preds       = []
    true_labels = []
    bar = tqdm(data_loader, desc="Evaluating", leave=False)
    with torch.no_grad():
        for batch in bar:
            input_ids      = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels         = batch['labels'].to(device)
            outputs        = model(input_ids=input_ids, attention_mask=attention_mask)
            loss           = loss_fn(outputs.logits, labels)
            total_loss    += loss.item()
            preds.append(torch.sigmoid(outputs.logits).cpu())
            true_labels.append(labels.cpu())
            bar.set_postfix(loss=f"{loss.item():.4f}")
    preds       = torch.cat(preds)
    true_labels = torch.cat(true_labels)
    return total_loss / len(data_loader), preds, true_labels

history       = []
best_val_loss = float('inf')
patience      = 2
no_improve    = 0

for epoch in range(EPOCHS):

    print(f"Epoch {epoch+1}/{EPOCHS}")


    train_loss = train_epoch(model, train_loader, loss_fn, optimizer, device, scheduler)
    val_loss, preds, true_labels = eval_model(model, val_loader, loss_fn, device)

    print(f"Train Loss : {train_loss:.4f}")
    print(f"Val Loss   : {val_loss:.4f}")

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        no_improve    = 0
        torch.save(model.state_dict(), 'bert_model.pth')
        print(f" Best model saved (val_loss={val_loss:.4f})")
    else:
        no_improve += 1
        print(f"  No improvement ({no_improve}/{patience})")
        if no_improve >= patience:
            print("Early stopping triggered.")
            break

    history.append({'epoch': epoch+1, 'train_loss': train_loss, 'val_loss': val_loss})

tokenizer.save_pretrained('tokenizer/')
print(f"\n Training complete! Best val loss: {best_val_loss:.4f}")

history_df = pd.DataFrame(history)
history_df.to_csv('training_history.csv', index=False)
print(history_df)

plt.figure(figsize=(8, 4))
plt.plot(history_df['epoch'], history_df['train_loss'], 'o-', label='Train Loss', color='#e74c3c')
plt.plot(history_df['epoch'], history_df['val_loss'],   's--', label='Val Loss',  color='#3498db')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training vs Validation Loss')
plt.legend()
plt.tight_layout()
plt.savefig('loss_plot.png', dpi=150)
plt.show()

# Load best saved model for evaluation
model.load_state_dict(torch.load('bert_model.pth', map_location=device))
_, preds, true_labels_eval = eval_model(model, val_loader, loss_fn, device)

preds_np       = preds.numpy()
true_labels_np = true_labels_eval.numpy()

# Find best threshold per label — wider range, finer steps
print("Finding best threshold per label...\n")
best_thresholds = {}
for i, label in enumerate(LABEL_COLS):
    best_f1 = 0
    best_t  = 0.5
    for t in np.arange(0.1, 0.9, 0.02):   # wider range + finer steps vs v2
        p = (preds_np[:, i] > t).astype(int)
        if p.sum() == 0:
            continue
        f1 = f1_score(true_labels_np[:, i], p, zero_division=0)
        if f1 > best_f1:
            best_f1 = f1
            best_t  = t
    best_thresholds[label] = round(float(best_t), 2)
    print(f"  {label:15s} → threshold: {best_t:.2f}  (F1: {best_f1:.4f})")

print("\nbest_thresholds =", best_thresholds)

# Use best thresholds for final evaluation
pred_labels = np.zeros_like(preds_np, dtype=int)
for i, label in enumerate(LABEL_COLS):
    pred_labels[:, i] = (preds_np[:, i] > best_thresholds[label]).astype(int)

accuracy        = accuracy_score(true_labels_np, pred_labels)
precision_micro = precision_score(true_labels_np, pred_labels, average='micro', zero_division=0)
precision_macro = precision_score(true_labels_np, pred_labels, average='macro', zero_division=0)
recall_micro    = recall_score(true_labels_np, pred_labels, average='micro', zero_division=0)
recall_macro    = recall_score(true_labels_np, pred_labels, average='macro', zero_division=0)
f1_micro        = f1_score(true_labels_np, pred_labels, average='micro', zero_division=0)
f1_macro        = f1_score(true_labels_np, pred_labels, average='macro', zero_division=0)
hl              = hamming_loss(true_labels_np, pred_labels)
roc_auc         = roc_auc_score(true_labels_np, preds_np, average='macro')


print("     EVALUATION METRICS")

print(f"Accuracy           : {accuracy:.4f}")
print(f"Precision (micro)  : {precision_micro:.4f}")
print(f"Precision (macro)  : {precision_macro:.4f}")
print(f"Recall    (micro)  : {recall_micro:.4f}")
print(f"Recall    (macro)  : {recall_macro:.4f}")
print(f"F1 Score  (micro)  : {f1_micro:.4f}")
print(f"F1 Score  (macro)  : {f1_macro:.4f}")
print(f"Hamming Loss       : {hl:.4f}")
print(f"ROC-AUC   (macro)  : {roc_auc:.4f}")

print("\nPer-label classification report:")
print(classification_report(true_labels_np, pred_labels, target_names=LABEL_COLS, zero_division=0))

"""## 🔧 Step 8: Predict Function"""

def predict(text):
    cleaned = clean_text(text)

    encoding = tokenizer(
        cleaned,
        truncation=True,
        padding='max_length',
        max_length=128,
        return_tensors='pt'
    )

    input_ids      = encoding['input_ids'].to(device)
    attention_mask = encoding['attention_mask'].to(device)

    with torch.no_grad():
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        probs   = torch.sigmoid(outputs.logits).cpu().numpy()[0]

    results  = {label: float(prob) for label, prob in zip(LABEL_COLS, probs)}
    detected = [label for label, prob in results.items() if prob >= best_thresholds[label]]

    print(f"Input    : {text}")
    print(f"Cleaned  : {cleaned}")
    print(f"Scores   : { {k: f'{v:.2%}' for k, v in results.items()} }")
    print(f"Detected : {detected if detected else ['✅ CLEAN']}")
    print()
    return results, detected

# ── Test cases ──

print("TEST CASES")

predict("you are beautiful")
predict("i miss you")
predict("i love you")
predict("beautiful")
predict("Have a great day!")
predict("I will kill you")
predict("You are such an idiot, go die")
predict("People like you should not exist")

from google.colab import files

files.download('bert_model.pth')
files.download('training_history.csv')
files.download('loss_plot.png')
files.download('eda_toxicity.png')

print(" All files downloaded!")
print("THRESHOLDS =", best_thresholds)

# ==========================================
# RAG STYLE UPGRADE (NO API KEY NEEDED)
# Toxicity Detection + Local Knowledge Base
# Run in Google Colab
# ==========================================

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# ------------------------------------------
# STEP 1: Create Knowledge Base (RAG Docs)
# ------------------------------------------
docs = [
    "Insult messages attack a person's intelligence or character.",
    "Threat messages contain violent or harmful intentions.",
    "Toxic language spreads hate and negativity.",
    "Best moderation action for insults is warning the user.",
    "Best moderation action for threats is block and report user.",
    "Polite communication avoids abusive words.",
    "Community guidelines ban hate speech and harassment."
]

# ------------------------------------------
# STEP 2: Build Retriever
# ------------------------------------------
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(docs)

# ------------------------------------------
# STEP 3: Detect Labels
# ------------------------------------------
def predict_labels(text):
    labels = []
    t = text.lower()

    if "idiot" in t or "stupid" in t:
        labels.append("insult")

    if "kill" in t or "die" in t:
        labels.append("threat")

    if "hate" in t:
        labels.append("toxic")

    if labels == []:
        labels.append("non-toxic")

    return labels

# ------------------------------------------
# STEP 4: RAG Retrieval
# ------------------------------------------
def retrieve_info(query):
    q = vectorizer.transform([query])
    scores = cosine_similarity(q, X)
    idx = scores.argmax()
    return docs[idx]

# ------------------------------------------
# STEP 5: Final AI Moderator
# ------------------------------------------
def rag_moderator(text):
    labels = predict_labels(text)

    retrieved = retrieve_info(text)

    print("\n===== SMART RAG MODERATOR =====")
    print("User Message :", text)
    print("Detected Labels :", labels)
    print("Retrieved Knowledge :", retrieved)

    if "threat" in labels:
        level = "HIGH"
        action = "Block + Report"
    elif "insult" in labels or "toxic" in labels:
        level = "MEDIUM"
        action = "Warn User"
    else:
        level = "SAFE"
        action = "Allow"

    print("Severity :", level)
    print("Recommended Action :", action)
    print("Polite Rewrite : Please communicate respectfully.")

# ------------------------------------------
# STEP 6: Run Demo
# ------------------------------------------
msg = input("Enter Message: ")
rag_moderator(msg)

